name: Accessibility Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run accessibility test
        run: npm run test:accessibility
